---
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
formats:
  - epub
python:
  install:
    - method: pip
      path: .
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
version: 2
