enableTelemetry: false
nodeLinker: 'node-modules'
npmAuditIgnoreAdvisories:
  - 1088208
  - 1095126
  - 1096993
  - 1097685
  - 'circular-json (deprecation)'
  - 'eslint (deprecation)'
  - 'glob (deprecation)'
  - 'gulp-util (deprecation)'
  - 'inflight (deprecation)'
  - 'rimraf (deprecation)'
plugins:
  - path: '.yarn/plugins/plugin-prettier-after-all-installed.cjs'
yarnPath: '.yarn/releases/yarn-4.9.1.cjs'
