#!/usr/bin/env python

# This file is part of open-in-mpv.
#
# Copyright 2020 Andrew Udvare
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from struct import pack
import json
import subprocess as sp
import sys

OPEN_IN_MPV_ARGS = ('./open-in-mpv', 'chrome://nothing')


def main():
    # type: () -> int
    data = json.dumps({'init': True})
    p0 = sp.Popen(  # pylint: disable=all
        OPEN_IN_MPV_ARGS,
        stdin=sp.PIPE,
        stdout=sp.PIPE)
    p0.communicate(input=pack('@i', len(data)) + data.encode('utf-8'))
    p0.wait()
    data = json.dumps({'url': sys.argv[1]})
    p = sp.Popen(  # pylint: disable=all
        OPEN_IN_MPV_ARGS,
        stdin=sp.PIPE,
        stdout=sp.PIPE)
    p.communicate(input=pack('@i', len(data)) + data.encode('utf-8'))
    p.wait()
    return 0 if p0.returncode == 0 and p.returncode == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
