# SPDX-License-Identifier: MIT
# Author: movrsi
from typing import Final, Self, Type

__all__ = ['PyHANDLE']

error: Final[tuple[Type[BaseException]]] = ...

class PyHANDLE:
    @property
    def handle(self) -> int: ...
    def Close(self) -> None: ...
    def close(self) -> None: ...
    def Detach(self) -> Self: ...
