---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: ${{ matrix.python-version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies (Poetry)
        run: poetry install --with=dev,docs,tests --all-extras
      - name: Install dependencies (Yarn)
        run: yarn
      - name: Mypy
        run: yarn mypy .
      - name: Pyright
        run: poetry run yarn pyright .
      - name: Ruff
        run: yarn ruff .
      - name: Check formatting
        run: yarn check-formatting
      - name: Check spelling
        run: yarn check-spelling
    strategy:
      matrix:
        python-version:
          - '3.12'
name: QA
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
