# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run: sudo apt-get install -y jq
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: ESLint
      run: npx eslint src/
    - name: Shellcheck install.sh
      run: shellcheck host/install.sh
    - name: check JSON files
      run: |
        jq . package.json >/dev/null
        jq . package-lock.json >/dev/null
        jq . .eslintrc.json >/dev/null
        jq . host/sh.tat.open_in_mpv.json.in >/dev/null
